#+author: Carlos Eduardo Martínez Aguilar
#+title: Temario de Matemáticas Avanzadas para la Física
#+LANGUAGE: esp
#+OPTIONS: tex:t
#+SETUPFILE: ~/Templates/latex-export.org

\noindent El nombre ``Matemáticas Avanzadas para la Física'' es bastante peculiar para un curso de un semestre de licenciatura, es un nombre muy poco descriptivo para una materia, uno al leerlo o escucharlo inmediatamente se puede preguntar ``¿A qué se refiere con ``Matemáticas Avanzadas''?'', ``¿Qué se abarca en un curso así?'' o ``¿No se supone que los primeros 5 semestres de la carrera de física se dedican al estudio de matemáticas avanzadas para la física?''. Si se está familiariazado con temas de física (se esperara que la mayor parte de las personas que toman este curso lo estén), entonces al escuchar ``Matemáticas Avanzadas'', uno se puede imaginar casi cualquier tema de matemáticas desarrollado durante el último siglo ya que es muy dificil encontrar ramas de la matemática que no se apliquen a los problemas físicos de los últimos años, desde topología algebraica hasta temas de estadística paramétrica.
Sin embargo, este es un curso preciso de licenciatura, por lo cual se debe acotar en los temas que se deber abordar, al revisar el temario de este curso, es claro que la mentalidad que se utilizó en su elaboración fue la de intentar abarcar los temas con aplicabilidad a la mayor parte de la física actual, al mismo tiempo se intentó mantener continuidad con el antiguo plan de estudios de física, en el cual la presente materia no existía y en su lugar se daba un curso de ``Funciones Especiales y Transformadas Integrales'' o ``FETI'' en corto. Viendo esto, queda más claro que ``Matemáticas Avanzadas para la Física'' se refiere más precisamente a ``métodos del analisis matemático, funcional y complejo para el estudio de soluciones de ecuaciones diferenciales ordinarias y parciales originarias de la física''.
Muchas presonas que han cusado esta materia nos han mencionado que el problema con una materia así es que los profesores tienden a enfocarse solamente en los métodos para terminar con el amplio temario, en lugar de desarrollar la intuición física y matemática para la resolución de éstos problemas. Nosotros como matemáticos impartiremos un curso de matemáticas, sin embargo esto no significa que nos enfocaremos en demostrar teoremas o solamente desarrollar la teoría, significa que expondremos la intución matemática detrás de los problemas sin perder el rigor matemático que permite generalizar estos métodos para otros problemas y al mismo tiempo sin ignorar la aplicabilidad de estos métodos. Intentaremos mostrar que a pesar que parece que son muchos métodos y mucha teoría, en realidad estos métodos son una extensión del álgebra lineal por medio del cálculo para la soluón de ecuaciones diferenciales. Aunado a estos pretendemos que esta materia sea una preparación matemática para la mecánicua cuántica por lo que haremos énfasis en problemas de mecánica cuántica y en la teoría espectral de operadores, además que utilizaremos la notación de Dirac  para espacios de Hilbert.\\
\vspace{1cm}

\noindent *TEMARIO* (El orden puede variar un poco).

1. Introducción y conceptos preliminares:
   - Espacios vectoriales y notación de Dirac.
   - Espacios Hilbert como espacios vectoriales de dimensión infinita.
   - Funcionales lineales, operadores y sus representaciones.
   - Formalismo de la teoría de la medida y el teorema de Riemann-Lebesgue.
   - Repaso de convergencia de series y variable compleja.

2. Análisis de Fourier:
   - Series de Fourier.
   - Condiciones de Dirichlet.
   - Convergencia de las series de Fourier.
   - Teorema de Fourier.
   - Series ortogonales en 2 variables.
   - Aplicaciones.

3. Teoría de Strurm-Liouville
   - Operadores auto adjuntos.
   - Operadores diferenciales auto adjuntos.
   - Funciones propias y funciones de peso.
   - Funciones de Green para ecuaciones no homogeneas.

4. Ecuación de Laplace:
   - Ecuación de Laplace en 2 dimensiones.
   - Separación de Variables
   - Armónicos esféricos.
   - Ecuación de Laplace en coordenadas cilíndricas.
   - Ecuación y Funciones de Bessel.

5. Funciones Especiales y Polinomios Ortogonales:
   - Definición y Ejemplos.
   - Familias ortogonales de polinomios (Laguerre, Hermite, Legendre y otros).
   - Función generadora y Aplicaciones.
   - Definición de la función Beta y su relación con la función Gama.
   - Definición de la Delta de Dirac.
   - Función Zeta de Riemann.*

6. Ecuaciones de Onda:
   - Análisis Vectorial y Teorema de descomposición de Helmholtz.
   - La Cuerda y la membrana circular vibrantes
   - Condiciones de la frontera.
   - Ecuación de Helmholtz en una y dos dimensiones.
   - Solución en problemas con valores en la frontera (con el formalismo de Fourier).
   - Ecuación de Shrodinger como ecuación de onda y ejemplos.

7. Ecuaciones de Calor:
   - Solución fundamental.
   - El flujo de calor.
   - Movimiento Browniano*.

8. Distribuciones (funciones generalizadas):
   - Distribuciones.
   - Derivadas débiles.
   - La delta de dirac y la función de Heaviside.
   - Funciones de Schwartz y distribuciones temperadas.

9. Transformadas Integrales:
   - Transformada de Fourier.
   - Propiedades y aplicaciones de la transformada de Fourier.
   - Transformada de Laplace.
   - Propiedades y aplicaciones de la transformada de Laplace.
   - Relación con las transformadas de Fourier.
   - Transformada de Fourier discreta y algoritmos*.

10. Funciones de Green para ecuaciones diferenciales parciales:
    - Transformada de Fourier para la ecuación de calor.
    - Transformada de Fourier para la ecuación de onda.
    - La ecuación de Poisson.

Los temas con * se considerarrán como extra y sólo si hay tiempo.

*NOTA 1*: Sólo hemos mencionado los temas matemáticos, aunado a esto se verán varios ejemplos físicos con énfasis en la mecánica cuantica como el pozo cuántico, el oscilador armónico cuántico y el átomo de hidrógeno.

*NOTA 2*: Además de la bibliografía, se harán unas notas de clases.\\
\vspace{1cm}
*Bibliografía*:

- H.F. Weinberger ``A First Course In Partial Differential Equations With Complex Variables and Transform Methods'', Dover Books On Mathematics, New York.
- N.N. Lebedev ``Special Functions & Their Applications'', Dover Books On Mathematics, New York.
- Arfken, George B. et all, ``Mathematical Methods for Physicist, A Comprehensive Guide.'', Ed. Elsevier, Seventh Edition.
- Appfel, Walter, ``Mathematics for Physics & Physicists.'', Ed. Princeton University Press, 2007.
- Churchill R. V. and Brown J. W., ``Fourier Series and Boundary Value Problems'', Ed McGraw-Hill.
- Courant R and D. Hilbert, ``Methods of Mathematical Physics.'', vol. 1 y 2.
- Tijonov A, ``Ecuaciones de la Física Matemática'', Ed. MIR Moscu, Segunda edición, 1980.
- Vladimirov V. S. , ``Equations of Mathematical Physics'', Ed. URSS Moscow, 1996.
- E. Kreyszig ``Introductory Functional Analysis With Applications'', John Wily & Sons.
